#!/bin/bash -l
#
#SBATCH --job-name=mpi
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --time=00:03:00
#SBATCH --gres gpu:1

module load pmi
module load mpi/mpich-x86_64

mpirun ./opt_ber